version: '3.9'

services:
  back:
    build: .
    restart: always
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

volumes:
  db_data:
